name: Build Frontend and Install Backend

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ──────────────────────────────
      # 📦 Install Backend Dependencies
      # ──────────────────────────────
      - name: Setup Node.js (Backend)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Backend dependencies
        working-directory: backend
        run: npm install

      # ──────────────────────────────
      # 🎨 Build Frontend
      # ──────────────────────────────
      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build
        env:
          VITE_STREAM_API_KEY: ${{ secrets.VITE_STREAM_API_KEY }}
