name: Dump Secrets
on: workflow_dispatch

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump all secrets
        run: |
          echo "JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}"
          echo "MONGO_URI: ${{ secrets.MONGO_URI }}"
          echo "NODE_ENV: ${{ secrets.NODE_ENV }}"
          echo "PORT: ${{ secrets.PORT }}"
          echo "STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}"
          echo "STEAM_API_SECRET: ${{ secrets.STEAM_API_SECRET }}"
          echo "VITE_STREAM_API_KEY: ${{ secrets.VITE_STREAM_API_KEY }}"
