name: Build Frontend and Install Backend

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
<<<<<<< HEAD

      # ──────────────────────────────
      # 📦 Install Backend Dependencies
      # ──────────────────────────────
      - name: Setup Node.js (Backend)
=======
      
      # Setup Node.js
      - name: Setup Node.js
>>>>>>> 82fc33d0b29b160780c703cfd4cc17b83118b440
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
<<<<<<< HEAD
          cache-dependency-path: backend/package-lock.json
=======
>>>>>>> 82fc33d0b29b160780c703cfd4cc17b83118b440

      # Install Backend dependencies
      - name: Install Backend dependencies
        working-directory: backend
<<<<<<< HEAD
        run: npm install

      # ──────────────────────────────
      # 🎨 Build Frontend
      # ──────────────────────────────
      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
=======
        run: npm ci
>>>>>>> 82fc33d0b29b160780c703cfd4cc17b83118b440

      # Install Frontend dependencies
      - name: Install Frontend dependencies
        working-directory: frontend
        run: npm ci
      
      # Build Frontend
      - name: Build Frontend
        working-directory: frontend
        run: npm run build
        env:
          VITE_STREAM_API_KEY: ${{ secrets.VITE_STREAM_API_KEY }}
